# WKE BaaS Deployment
services:
  db:
    image: postgres:17
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - traefik
  postgrest:
    image: postgrest/postgrest:v12.2.8
    depends_on:
      - db
    restart: always
    expose:
      - 3000
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://${BAAS_HOST}/pgrst
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: guest
      PGRST_OPENAPI_MODE: ignore-privileges
      PGRST_JWT_SECRET: ${JWK_PUBLIC_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgrest.rule=Host(`${BAAS_HOST}`) && PathPrefix(`/pgrst`)"
      - "traefik.http.routers.postgrest.entrypoints=web"
      - "traefik.http.middlewares.postgrest-stripprefix.stripPrefix.prefixes=/pgrst"
      - "traefik.http.routers.postgrest.middlewares=postgrest-stripprefix@docker"
volumes:
  db-data:
networks:
  default:
  traefik:
    external: true
